# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c136c033c85e4f9957deb868c42662bab8e3f64c27ec507eb57cf2e3b0e92271ded107557498f923b11d38ac4b951a4556e332da85e516cf6272acf3dad0929c

test:
  secret_key_base: a228e0ce3b787df6caa5fa3be88fbdd5ead6c482760ed0449184ac9a2a07b9bcd9e01abd551514544ed662474b033f03253e59ff77fdd5d35f6bf902d441f022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
