# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b37fbf7d6111600be18c6963c4d42aeff34eafde02095e35c6086a1a6c22bbbd03f0bf476b54cd8643f77a649287f7afe6e20a88963e4217762c422e7bd8abe0

test:
  secret_key_base: 88ed0817ede816ea785e9b494ecbed118da527d73a1961369a74d875368f86c1a45be37560c0fc2c169f01dd8c3839e977552f24b51ea2febf2075c032d40d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
